name: Deploy to Droplet staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            cd /var/www/html/shipment/staging

            git pull origin main

            sudo systemctl restart nginx

            echo "Deployment completed successfully."
